<?php

namespace ContainerEXZ0Ssd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XYNqNbLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XYNqNbL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XYNqNbL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeeRep' => ['privates', 'App\\Repository\\EmployeesRepository', 'getEmployeesRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'employeeRep' => 'App\\Repository\\EmployeesRepository',
            'entityManagerInterface' => '?',
        ]);
    }
}
