<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKGnMi6o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKGnMi6o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKGnMi6o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKGnMi6o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKGnMi6o\App_KernelDevDebugContainer([
    'container.build_hash' => 'KGnMi6o',
    'container.build_id' => '06eefe70',
    'container.build_time' => 1709481665,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKGnMi6o');
